## One-Hot Dönüşümü ve Dummy Değişken Tuzağı

*Bir önceki bölümde kategorik değişkene label encoding yaptıktan sonra ortaya çıkan ve gerçekte var olmayan yapay bir sıralama ve mesafe ilişkisinden bahsetmiştik. Bunun çözümü One-Hot Dönüşümü'dür. Bu dönüşümü yaparken de ortaya Dummy değişken tuzağı dediğimiz bir problem ortaya çıkıyor. Bunun çözümünden de bahsedeceğiz.*

*Veri setimizi ve üzerinde yaptığımız işlemleri hatırlayalım:*

In [1]:
import seaborn as sns
df = sns.load_dataset("tips")
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [2]:
#0-1 Dönüşümü

In [3]:
from sklearn.preprocessing import LabelEncoder
lbe = LabelEncoder()

In [4]:
df["new_sex"] = lbe.fit_transform(df["sex"])

In [5]:
df.head()

   total_bill   tip     sex smoker  day    time  size  new_sex
0       16.99  1.01  Female     No  Sun  Dinner     2        0
1       10.34  1.66    Male     No  Sun  Dinner     3        1
2       21.01  3.50    Male     No  Sun  Dinner     3        1
3       23.68  3.31    Male     No  Sun  Dinner     2        1
4       24.59  3.61  Female     No  Sun  Dinner     4        0

In [6]:
#1 ve 'Diğerleri' Dönüşümü

In [7]:
df.head()

   total_bill   tip     sex smoker  day    time  size  new_sex
0       16.99  1.01  Female     No  Sun  Dinner     2        0
1       10.34  1.66    Male     No  Sun  Dinner     3        1
2       21.01  3.50    Male     No  Sun  Dinner     3        1
3       23.68  3.31    Male     No  Sun  Dinner     2        1
4       24.59  3.61  Female     No  Sun  Dinner     4        0

In [8]:
import numpy as np
df["new_day"] = np.where(df["day"].str.contains("Sun"), 1, 0)

In [9]:
df.head(100)

    total_bill   tip     sex smoker  day    time  size  new_sex  new_day
0        16.99  1.01  Female     No  Sun  Dinner     2        0        1
1        10.34  1.66    Male     No  Sun  Dinner     3        1        1
2        21.01  3.50    Male     No  Sun  Dinner     3        1        1
3        23.68  3.31    Male     No  Sun  Dinner     2        1        1
4        24.59  3.61  Female     No  Sun  Dinner     4        0        1
..         ...   ...     ...    ...  ...     ...   ...      ...      ...
95       40.17  4.73    Male    Yes  Fri  Dinner     4        1        0
96       27.28  4.00    Male    Yes  Fri  Dinner     2        1        0
97       12.03  1.50    Male    Yes  Fri  Dinner     2        1        0
98       21.01  3.00    Male    Yes  Fri  Dinner     2        1        0
99       12.46  1.50    Male     No  Fri  Dinner     2        1        0

[100 rows x 9 columns]

In [10]:
#Çok Sınıflı Dönüşüm

In [11]:
from sklearn.preprocessing import LabelEncoder
lbe = LabelEncoder()

In [12]:
lbe.fit_transform(df["day"])

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 3])

In [13]:
df.head()

   total_bill   tip     sex smoker  day    time  size  new_sex  new_day
0       16.99  1.01  Female     No  Sun  Dinner     2        0        1
1       10.34  1.66    Male     No  Sun  Dinner     3        1        1
2       21.01  3.50    Male     No  Sun  Dinner     3        1        1
3       23.68  3.31    Male     No  Sun  Dinner     2        1        1
4       24.59  3.61  Female     No  Sun  Dinner     4        0        1

In [14]:
import pandas as pd
df_one_hot = pd.get_dummies(df, columns = ["sex"], prefix = ["sex"], dtype = int)

In [15]:
df_one_hot.head()

,total_bill,tip,smoker,day,time,size,new_sex,new_day,sex_Male,sex_Female
0,16.99,1.01,No,Sun,Dinner,2,0,1,0,1
1,10.34,1.66,No,Sun,Dinner,3,1,1,1,0
2,21.01,3.50,No,Sun,Dinner,3,1,1,1,0
3,23.68,3.31,No,Sun,Dinner,2,1,1,1,0
4,24.59,3.61,No,Sun,Dinner,4,0,1,0,1

*Orijinal veri setindeki "sex" kategorik değişken sınıflarının her birini nümerik değişkenlere dönüştürdük ve bu değişken sınıflarını 1 ve 0 olarak tanımladık. Örneğin indeks 1'deki gözlem biriminde müşteri erkek, indeks 0'da müşteri kadın.*

*Burada dummy değişken tuzağı ortaya çıkıyor. Bir veri setindeki değişkene one-hot dönüşümü uyguladıktan sonra ortaya çıkan değişkenler birbirleri üzerinden oluşturulabiliyorsa bu dummy değişken tuzağı oluyor. Yani burada sex_Male değişkenine bakarak sex_Female değişkenini oluşturabiliriz ya da tam tersini uygulayarak oluşturabiliriz. Yani bu iki değişken şu an aynı bilgiyi taşıyor. Bu işlem sonrasında dönüşüm uyguladığımız kategorik değişkenin sınıf sayısından 1 eksik dummy değişken olması gerekir. Değişkenin orijinal halinde olduğu gibi iki değil bir sınıf olmalı.*

In [16]:
pd.get_dummies(df, columns = ["day"], prefix = ["day"], dtype = int)

,total_bill,tip,sex,smoker,time,size,new_sex,new_day,day_Thur,day_Fri,day_Sat,day_Sun
0,16.99,1.01,Female,No,Dinner,2,0,1,0,0,0,1
1,10.34,1.66,Male,No,Dinner,3,1,1,0,0,0,1
2,21.01,3.50,Male,No,Dinner,3,1,1,0,0,0,1
3,23.68,3.31,Male,No,Dinner,2,1,1,0,0,0,1
4,24.59,3.61,Female,No,Dinner,4,0,1,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Dinner,3,1,0,0,0,1,0
240,27.18,2.00,Female,Yes,Dinner,2,0,0,0,0,1,0
241,22.67,2.00,Male,Yes,Dinner,2,1,0,0,0,1,0
242,17.82,1.75,Male,No,Dinner,2,1,0,0,0,1,0
243,18.78,3.00,Female,No,Dinner,2,0,0,1,0,0,0

#### Peki Bu İşlemi Yapmamızdaki Temel Sebep Ne ?

*Burada dönüşüm uyguladığımız kategorik değişken sınıflarının etkisini veri setinde daha hissedilebilir olmasını sağladık. Algoritmaya ilgili değişkenin ağırlığını kazandırma imkanı sağlıyor. Örnek üzerinden açıklayalım : 10 sınıflı bir kategorik değişken var ve bu değişken veri setimizin kilit değişkeni olsun ve algoritma bu değişken üzerinden yazılsın. Bu 10 sınıflı değişkene dönüşüm uyguladığımızda yeni veri setimizde bu 10 sınıf da nümerik olarak temsil edilecek. Bu işlem ilgili kategorik değişkenin gözlem bazında veri setindeki ağırlığını arttırıyor. Aynı zamanda nümerik dönüştürme işlemini de aradan çıkartmış oluyoruz. Yani aslında algoritmaya diyoruz ki bak bu değişkenin şu kadar sınıfı var ve bu değişken benim veri setimin kilit noktası. Senin için nümerik hale de getirdim kendini buna göre eğit demiş oluyoruz.*

*One-Hot Dönüşümü'nde üzerinde dönüşüm yapmak istediğimiz kategorik değişkenin sınıf sayısı arttıkça bu sınıfların birbirleri üzerinden dönüşüm yapılabilirliği de güçleşiyor. Yani çok sınıflı kategorik değişkenlerin dönüşümü yerinde uygulunacak bir hamledir. Fakat "sex" kategorik değişken örneğinde olduğu gibi dummy tuzağı olup olmama durumu her zaman kontrol edilmelidir.*