### İş Uygulaması: Anasayfa İçerik Stratejisi Belirlemek

*Bir web sitesinin ortalama ziyaret süresinin uzun olması, hemen çıkış oranı gibi istatistiksel bilgilerin düşük olması o web sitesinin başarı metriklerindendir. Elimizde 3 tarz haber sunma tarzı var (A, B ,C). En iyi sunma tarzının belirlenmesi gerekiyor.*

- **Problem:**
  Anasayfa'da geçirilen süre artırılmak isteniyor

- **Detaylar:**
  - Bir web sitesi için başarı kriterleri: ortalama ziyaret süresi, hemen çıkış oranı vb
  - Uzun zaman geçiren kullanıcıların reklamlara daha fazla tıkladığı ve markaya olan bağlılıklarının arttığı biliniyor.
  - Buna yönelik olarak benzer haberler farklı resimler ya da farklı formatlarda hazırlanarak oluşturulan test gruplarına gösteriliyor.
  - A: Doğal Şekilde, B: Yönlendirici, C: İlgi Çekici

*Bir Veri Bilimci olarak hangi haber sunma tarzının en çok ziyaret edilmeyi sağladığını yapacağımız testlerle belirlememiz gerekiyor. Verinin bize sağlıklı bir şekilde gelmesi ve veriyi doğru bir şekilde yorumlamak gerekir.*

*3 gruptan da veri seti geliyor. Veri seti kullanıcıların A, B, C grup özelliklerini taşıyan web sitesinde ortalama geçirilen süre bilgilerini taşıyor. Veri setleri excel formunda geliyor.*

## Varyans Analizi

$$
\begin{aligned}
H_0&: M_1 = M_2 = M_3 \quad \text{(Grup ortalamaları arasında ist. anl. farklılık yoktur)} \\
H_1&: \text{Fark vardır.}
\end{aligned}
$$

In [1]:
import pandas as pd

A = pd.DataFrame([28,33,30,29,28,29,27,31,30,32,28,33,25,29,27,31,31,30,31,34,30,32,31,34,28,32,31,28,33,29])

B = pd.DataFrame([31,32,30,30,33,32,34,27,36,30,31,30,38,29,30,34,34,31,35,35,33,30,28,29,26,37,31,28,34,33])

C = pd.DataFrame([40,33,38,41,42,43,38,35,39,39,36,34,35,40,38,36,39,36,33,35,38,35,40,40,39,38,38,43,40,42])

dfs = [A, B, C]

ABC = pd.concat(dfs, axis = 1)
ABC.columns = ["GRUP_A","GRUP_B","GRUP_C"]
ABC.head()

   GRUP_A  GRUP_B  GRUP_C
0      28      31      40
1      33      32      33
2      30      30      38
3      29      30      41
4      28      33      42

#### Varsayım Kontrolü

In [2]:
#Normal Varsayımı
from scipy.stats import shapiro

In [3]:
shapiro(ABC["GRUP_A"])

ShapiroResult(statistic=np.float64(0.9697430293916081), pvalue=np.float64(0.5321675250468361))

In [4]:
shapiro(ABC["GRUP_B"])

ShapiroResult(statistic=np.float64(0.9789855288537495), pvalue=np.float64(0.7979814669020528))

In [5]:
shapiro(ABC["GRUP_C"])

ShapiroResult(statistic=np.float64(0.9579198548620552), pvalue=np.float64(0.27381521754487215))

*Normal varsayımı: Teorik dağılım ile normal dağılımı arasında anlamlı bir fark yoktur. 3 grup için de p-value değeri alpha değeri olan 0.05'den büyük. Yani H0'ı reddedemiyoruz, ki bu da istediğimiz bir durum.*

In [6]:
#Varyans Homojenliği Varsayımı
from scipy.stats import levene

In [7]:
levene(ABC["GRUP_A"], ABC["GRUP_B"], ABC["GRUP_C"])

LeveneResult(statistic=np.float64(1.0267403645055275), pvalue=np.float64(0.3624711011741697))

*Varsayım: 3 grup arasında da homojen bir dağılım mevcuttur. H0 bunu söylüyor. p-value 0.05'ten çok büyük. H0 hipotezi reddedilemez.*

*Burada gözlemlerin(A, B, C) birbirinden bağımsız olduğunu kabul ediyoruz.*

#### Hipotez Testi

In [8]:
from scipy.stats import f_oneway

In [9]:
f_oneway(ABC["GRUP_A"], ABC["GRUP_B"], ABC["GRUP_C"])

F_onewayResult(statistic=np.float64(74.69278140730431), pvalue=np.float64(1.3079050746811492e-19))

In [10]:
#Daha güzel yöntem
print('{:0.5f}'.format(f_oneway(ABC["GRUP_A"], ABC["GRUP_B"], ABC["GRUP_C"])[1]))

0.00000

*p-value değerimiz 0.05'ten çok küçük. H0'ı reddektik. Yani web sitesi tasarımlarının kullanıcılarn web sitesini ziyaret etme süreleri üzerinde kayda değer bir etkisi var.*

In [11]:
ABC.describe().T

        count       mean       std   min    25%   50%    75%   max
GRUP_A   30.0  30.133333  2.224214  25.0  28.25  30.0  31.75  34.0
GRUP_B   30.0  31.700000  2.937862  26.0  30.00  31.0  34.00  38.0
GRUP_C   30.0  38.100000  2.808239  33.0  36.00  38.0  40.00  43.0

*ilgi çekici tasarımlara sahip web siteleri kullanıcıların en çok ilgisini çekiyor.*

*Diyelim ki varsayımları sağlayamadık. Ne yapacaktık ? Tabi ki **nonparametrik hipotez testi**.*

In [12]:
from scipy.stats import kruskal

In [13]:
kruskal(ABC["GRUP_A"], ABC["GRUP_B"], ABC["GRUP_C"])

KruskalResult(statistic=np.float64(54.19819735523783), pvalue=np.float64(1.7022015426175924e-12))

**(1.70 * e^-12) değeri 0'a çok yakın. Yani H0'ı reddederiz.**